[app]
name = "Rubber Duck"
debug = false

[window]
width = 400
height = 300

[paths]
assets = "assets"

[model]
shape = "cube"
model = ""
shape_color_r = 1.0
shape_color_g = 0.43529411764705883
shape_color_b = 0.5529411764705883
